### ISSUE TITLE
TypeScript cannot find name 'module' in unit tests - should now be 'angular.mock.module' ?

### ISSUE THREAD

**Issue by egeland** [dustinspecker/generator-ng-poly#189]
I'm not sure exactly when this started, as I've done a few updates, but now TS complains about the line

```
beforeEach(module('mymodulename'));
```
with an error like
```
app/core/mymodulename-service_test.ts(12,14): 2304 Cannot find name 'module'.
```

I'm editing in Atom, and tslint also highlights the _module_ as not found.
![image](https://cloud.githubusercontent.com/assets/1281379/9727974/acc49b76-563f-11e5-89d8-622af379e271.png)

I think (please correct me if I'm wrong) that we need to change `module` to `angular.mock.module` so it will find the right 'module' to use - there's a comment in the `angularjs/angular-mocks.d.ts` file to that effect:
>    //Use `angular.mock.module` instead of `module`, as `module` conflicts with commonjs.

Making this change eliminated my errors.

I'll submit a PR to change these references.

**Comment by dustinspecker** [comment]
Oh, interesting. Just played around with this. Looks like you have an updated version of the Angular Mock typings, which doesn't have `module` supported. ng-poly's old version has support for `mock` and `angular.mock.module`. I'll look into bumping the TSD versions soon.

Just be sure to update your `tsd.json` with the recent [SHA](https://github.com/borisyankov/DefinitelyTyped/commits/master) in case other folks on your team run into issues.

Thank you for the PR!

**Comment by rupeshtiwari** [comment]
I also found the same issue. I had module in my tests now I have to update all of them since I upgraded my angular to 1.5 They have comment below in the type definition file 
//Use `angular.mock.module` instead of `module`, as `module` conflicts with commonjs.
